### ISSUE TITLE
Error when run examples

### ISSUE THREAD

**Issue by YangBain** [NeuromorphicProcessorProject/snn_toolbox#13] opened 2018-06-20 09:37 UTC
When I run examples, I get the following error. Could you give me some suggestions? Thank you very much.

snntoolbox <./examples/models/vgg16/config> -t
Traceback (most recent call last):
  File "/home/beans/anaconda3/envs/py27/bin/snntoolbox", line 11, in <module>
    sys.exit(main())
  File "/home/beans/snn_toolbox/snntoolbox/bin/run.py", line 38, in main
    filepath = os.path.abspath(args.config_filepath)
  File "/home/beans/anaconda3/envs/py27/lib/python3.6/posixpath.py", line 371, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by rbodo** [comment] 2018-06-20 13:49
Hi YangBain, please post the command you use to run the example. It seems you are not specifying a path to the config file.

**Comment by YangBain** [comment] 2018-06-21 06:49
Hi，
Under the snn_toolbox, I use snntoolbox <./examples/models/vgg16/config> -t. Thank you very much.



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Bodo Rueckauer <notifications@github.com>
发送时间: Wednesday, June 20, 2018 10:49:21 PM
收件人: NeuromorphicProcessorProject/snn_toolbox
抄送: Bin Yang; Author
主题: Re: [NeuromorphicProcessorProject/snn_toolbox] Error when run examples (#13)


Hi YangBain, please post the command you use to run the example. It seems you are not specifying a path to the config file.

―

**Comment by rbodo** [comment] 2018-06-21 07:36
Please try without the <>.

By the way, the VGG example will not work unless you have a VGG model in Keras yourself. We could not upload our VGG model onto the repository for memory reasons. I suggest you try the LeNet examples first.

**Comment by ljxgit** [comment] 2018-07-05 09:04
I run the LeNet example in Keras,  the command is "snntoolbox -t ./examples/models/lenet5/keras/config", and there is an error, "AttributeError: 'Conv2D' object has no attribute '_inbound_nodes'"
Could you give me some suggestions? Thank you very much!  @rbodo

**Comment by rbodo** [comment] 2018-07-05 22:18
Duplicate of #14

**Closed by rbodo** 2018-07-05 22:18 UTC
